=== alopez244/FlexManSys/src/resources/TypeOfProduct.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- editado con XMLSpy v2020 sp1 (x64) (http://www.altova.com) por  (University of the Basque Country) -->
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<xs:schema xmlns="ManufacturingPlan" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="ManufacturingPlan" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="./Base Schemas/Operations.xsd"/>
	<xs:simpleType name="TState">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Accepted"/>
			<xs:enumeration value="Planned"/>
			<xs:enumeration value="Production"/>
			<xs:enumeration value="Completed"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Raw Material -->
	<xs:element name="rawMaterial">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TTypeOfProduct">
		<xs:choice>
			<xs:element ref="rawMaterial" maxOccurs="1"/>
			<xs:sequence>
				<xs:element name="action" type="TAction" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="TypeOfProduct" type="TTypeOfProduct"/>
			</xs:sequence>
		</xs:choice>
		<xs:attribute name="productType" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="refRecipe" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="TypeOfProduct" type="TTypeOfProduct"/>
</xs:schema>

=== alopez244/FlexManSys/src/resources/ProductInstances/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2020 sp1 (x64) (http://www.altova.com) por  (University of the Basque Country) -->
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<TypeOfProduct xmlns="ManufacturingPlan" productType="4" refRecipe="recipe02" description="Elaborated Product IPB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ManufacturingPlan ../TypeOfProduct.xsd">
	<action id="1" type="pick_and_place" description="robot moving piece"/>
	<TypeOfProduct productType="IPB_4" description="Industrial Plastic Base 4">
		<action id="3" type="indexing" description="indexing process"/>
		<TypeOfProduct productType="IPB_3" description="Industrial Plastic Base 3">
			<action id="1" type="pick_and_place" description="robot moving piece"/>
			<TypeOfProduct productType="IPB_2" description="Industrial Plastic Base 2">
				<action id="2" type="punching" description="punching process"/>
				<TypeOfProduct productType="IPB_1" description="Industrial Plastic Base 1">
					<action id="1" type="pick_and_place" description="robot moving piece"/>
					<TypeOfProduct productType="IPB" description="Industrial Plastic Base">
						<rawMaterial id="IPB" description="Industrial Plastic Base"/>
					</TypeOfProduct>
				</TypeOfProduct>
			</TypeOfProduct>
		</TypeOfProduct>
	</TypeOfProduct>
</TypeOfProduct>

=== alopez244/FlexManSys/src/resources/ProductInstances/BP1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2020 sp1 (x64) (http://www.altova.com) por  (University of the Basque Country) -->
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<TypeOfProduct xmlns="ManufacturingPlan" productType="BP1" refRecipe="recipe02" description="Big product 1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ManufacturingPlan ../TypeOfProduct.xsd">
	<action id="4" type="pick_and_place" description="place cover"/>
	<TypeOfProduct productType="BB_B2" description="BB_A + upper bearing">
		<action id="3" type="insert" description="insert upper bearing"/>
		<TypeOfProduct productType="BB_A" description="BB_B + axis">
			<action id="2" type="insert" description="insert axis"/>
			<TypeOfProduct productType="BB_B" description="BB + lower bearing">
				<action id="1" type="insert" description="insert lower bearing"/>
				<TypeOfProduct productType="BB" description="Big base">
					<rawMaterial id="BB" description="Big base"/>
				</TypeOfProduct>
			</TypeOfProduct>
		</TypeOfProduct>
	</TypeOfProduct>
</TypeOfProduct>

=== alopez244/FlexManSys/src/resources/ProductInstances/SP1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2020 sp1 (x64) (http://www.altova.com) por  (University of the Basque Country) -->
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<TypeOfProduct xmlns="ManufacturingPlan" productType="SP1" refRecipe="recipe03" description="Small product 1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ManufacturingPlan ../TypeOfProduct.xsd">
	<action id="8" type="pick_and_place" description="place cover"/>
	<TypeOfProduct productType="SB_B2" description="SB_A + upper bearing">
		<action id="7" type="insert" description="insert upper bearing"/>
		<TypeOfProduct productType="SB_A" description="SB_B + axis">
			<action id="6" type="insert" description="insert axis"/>
			<TypeOfProduct productType="SB_B" description="SB + lower bearing">
				<action id="5" type="insert" description="insert lower bearing"/>
				<TypeOfProduct productType="SB" description="Small base">
					<rawMaterial id="SB" description="Small base"/>
				</TypeOfProduct>
			</TypeOfProduct>
		</TypeOfProduct>
	</TypeOfProduct>
</TypeOfProduct>
