=== alopez244/FlexManSys/src/resources/ProductInstances/Product.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2018 sp1 (http://www.altova.com) by Marga Marcos (Escuela de IngenierÃ­a de Bilbao (UPV/EHU)) -->
<xs:schema xmlns="ManufacturingPlan" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="ManufacturingPlan" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="../Base Schemas/IEC62264.xsd"/>
	<xs:include schemaLocation="../Base Schemas/Operations.xsd"/>
	<!-- Raw Material -->
	<xs:attributeGroup name="TMResource">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>
		<xs:attribute name="resourceType" type="TResource" use="required" fixed="material"/>
		<xs:attribute name="assembly_type" type="TAssemblyType" use="optional"/>
		<xs:attribute name="assembly_relationship" type="TAssemblyRelationShip" use="optional"/>
	</xs:attributeGroup>
	<xs:element name="rawMaterial">
		<xs:complexType>
			<xs:attributeGroup ref="TMResource"/>
		</xs:complexType>
	</xs:element>
	<!-- Product -->
	<xs:attributeGroup name="process">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>
		<xs:attribute name="hierarchy_level" type="TRecipeHLevel" use="required" fixed="process"/>
		<xs:attribute name="assembly_type" type="TAssemblyType" use="optional"/>
		<xs:attribute name="assembly_relationship" type="TAssemblyRelationShip" use="optional"/>
	</xs:attributeGroup>
	<xs:complexType name="TProduct">
		<xs:choice>
			<xs:element ref="rawMaterial" maxOccurs="1"/>
			<xs:sequence>
				<xs:annotation>
					<xs:documentation>t1 and t2</xs:documentation>
				</xs:annotation>
				<xs:element name="simple_operation" type="SimpleOperation"/>
				<xs:choice>
					<xs:element ref="rawMaterial"/>
					<xs:element name="Product" type="TProduct"/>
				</xs:choice>
			</xs:sequence>
			<xs:sequence>
				<xs:annotation>
					<xs:documentation>t3</xs:documentation>
				</xs:annotation>
				<xs:element name="complex_operation" type="ComplexOperation"/>
				<xs:element name="Product" type="TProduct" minOccurs="2" maxOccurs="2"/>
			</xs:sequence>
		</xs:choice>
		<xs:attributeGroup ref="process"/>
	</xs:complexType>
	<xs:element name="Product" type="TProduct"/>
</xs:schema>

=== alopez244/FlexManSys/src/resources/ProductInstances/P_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<Product xmlns="ManufacturingPlan" id="P_03" description="Product3 (Base+Axis+Cover)" hierarchy_level="process" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ManufacturingPlan Product.xsd">
  <complex_operation id="C_01" type="assembly" description="Assemble the cover with the unfinished product Base+Axis"/>
  <Product id="B_A" description="Unfinished product result of joining the base and the axis" hierarchy_level="process">
    <simple_operation id="S_02" type="insert_axis" description="Insert de axis in the base"/>
	<Product id="B" description="Base" hierarchy_level="process">
		<rawMaterial id="B" description="Base" resourceType="material"/>
	</Product>
  </Product>
  <Product id="C" description="Cover" hierarchy_level="process">
    <rawMaterial id="C" description="Cover" resourceType="material"/>
  </Product>
</Product>
