=== alopez244/FlexManSys/src/resources/Version 07-04-21/ResInstances/Station.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- editado con XMLSpy v2020 sp1 (x64) (http://www.altova.com) por  (University of the Basque Country) -->
<!-- edited with XMLSpy v2018 sp1 (http://www.altova.com) by Marga Marcos (Escuela de Ingeniería de Bilbao (UPV/EHU)) -->
<xs:schema xmlns="station" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" targetNamespace="station" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="../Base Schemas/IEC62264.xsd"/>
	<xs:redefine schemaLocation="../Base Schemas/Operations.xsd">
		<xs:complexType name="SimpleOperation">
			<xs:complexContent>
				<xs:extension base="SimpleOperation">
					<xs:attribute name="executionTime" type="xs:time" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		<xs:complexType name="ComplexOperation">
			<xs:complexContent>
				<xs:extension base="ComplexOperation">
					<xs:attribute name="executionTime" type="xs:time" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:redefine>
	<!-- ========= STATION ============ -->
	<xs:element name="palletIn">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="xPos" type="xs:double" use="required"/>
			<xs:attribute name="yPos" type="xs:double" use="required"/>
			<xs:attribute name="zPos" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="palletOut">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="xPos" type="xs:double" use="required"/>
			<xs:attribute name="yPos" type="xs:double" use="required"/>
			<xs:attribute name="zPos" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- TConsumable: material consumible de la estación -->
	<xs:simpleType name="TypeOfConsumable">
		<xs:restriction base="xs:string">
			<xs:enumeration value="axle"/>
			<xs:enumeration value="bearing"/>
			<xs:enumeration value="bolt"/>
			<xs:enumeration value="cover"/>
			<xs:enumeration value="filter"/>
			<xs:enumeration value="nut"/>
			<xs:enumeration value="sleeve"/>
			<xs:enumeration value="welding_wire"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="consumable">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="type" type="TypeOfConsumable" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- Buffer: almacenes intermedios de estaciones -->
	<xs:element name="buffer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="consumable" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="current" type="xs:integer" use="required"/>
			<xs:attribute name="max" type="xs:integer" use="required"/>
			<xs:attribute name="warning" type="xs:integer" use="required"/>
			<xs:attribute name="xPos" type="xs:double" use="required"/>
			<xs:attribute name="yPos" type="xs:double" use="required"/>
			<xs:attribute name="zPos" type="xs:double" use="required"/>
			<xs:attribute name="consumable_id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="TToolSet">
		<xs:restriction base="xs:string">
			<xs:enumeration value="cutter"/>
			<xs:enumeration value="die_set"/>
			<xs:enumeration value="drill"/>
			<xs:enumeration value="gripper"/>
			<xs:enumeration value="wleding_torch"/>
		</xs:restriction>
		<!-- definir qué herramienta tiene la máquina, en función de su valor el tiempo de cambio de utillaje cambia-->
	</xs:simpleType>
	<xs:element name="tool">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="type" type="TToolSet" use="required"/>
			<xs:attribute name="changeoverT" type="xs:time" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- changeoverT: tiempo de cambio de herramienta -->
	<xs:element name="station">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="palletIn" minOccurs="1" maxOccurs="2"/>
				<xs:element ref="palletOut" minOccurs="1" maxOccurs="2"/>
				<xs:element ref="buffer" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="tool" minOccurs="1" maxOccurs="unbounded"/>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="simple_operation" type="SimpleOperation"/>
					<xs:element name="complex_operation" type="ComplexOperation"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:key name="consumableID">
			<xs:selector xpath="./buffer/consumable"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="refConsumableID" refer="consumableID">
			<xs:selector xpath="./buffer"/>
			<xs:field xpath="@consumable_id"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== alopez244/FlexManSys/classes/resources/ResInstances/EquipmentResourceInstances/Station1.xml
<?xml version="1.0" encoding="UTF-8"?>
<station xmlns="station" id="ST01" description="Station 1 (Work Unit)" resourceType="equipment" level="work_unit" sn="KR3-R540-001" physicalLocation="researchLab,productionLine1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="station ../Station.xsd">
<palletIn id="PI1_ST01" xPos="80" yPos="80" zPos="50"/>
		<palletIn id="PI2_ST01" xPos="520" yPos="80" zPos="50"/>
		<palletOut id="PO1_ST01" xPos="620" yPos="380" zPos="50"/>
		<buffer id="B1_ST01" description="Buffer 1 contains bearings" current="10" max="10" warning="5" xPos="220" yPos="580" zPos="40" consumable_id="C1_B1_ST01">
			<consumable id="C1_B1_ST01" description="Lower Bearing" type="bearing" resourceType="material"/>
		</buffer>
		<buffer id="B2_ST01" description="Buffer 2 contains bearings" current="10" max="10" warning="5" xPos="320" yPos="580" zPos="40" consumable_id="C2_B2_ST01">
			<consumable id="C2_B2_ST01" description="Higher Bearing" type="bearing" resourceType="material"/>
		</buffer>
		<buffer id="B3_ST01" description="Buffer 3 contains axes" current="10" max="10" warning="5" xPos="420" yPos="580" zPos="40" consumable_id="C3_B3_ST01">
			<consumable id="C3_B3_ST01" description="Shaft" type="axle" resourceType="material"/>
		</buffer>
		<buffer id="B4_ST01" description="Buffer 4 contains covers" current="10" max="10" warning="5" xPos="520" yPos="580" zPos="40" consumable_id="C4_B4_ST01">
			<consumable id="C4_B4_ST01" description="Cover" type="cover" resourceType="material"/>
		</buffer>
		<tool id="T1_ST01" type="gripper" changeoverT="00:15:00" description="Double gripper"/>
		<simple_operation id="S_01" type="place_cover" executionTime="00:00:05"/>
		<simple_operation id="S_02" type="insert_axis" executionTime="00:00:10"/>
		<simple_operation id="S_03" type="insert_and_place" executionTime="00:00:20"/>
		<complex_operation id="C_01" type="assembly" executionTime="00:00:10"/>
</station>

=== alopez244/FlexManSys/classes/resources/ResInstances/EquipmentResourceInstances/Station3.xml
<?xml version="1.0" encoding="UTF-8"?>
<station xmlns="station" id="ST03" description="Station_3_Work_Unit" resourceType="equipment" level="work_unit" sn="KR3-R540-002" physicalLocation="researchLab,productionLine3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="station ../Station.xsd">
	<palletIn id="PI1_ST03" xPos="80" yPos="80" zPos="50"/>
		<palletIn id="PI2_ST03" xPos="520" yPos="80" zPos="50"/>
		<palletOut id="PO1_ST03" xPos="620" yPos="380" zPos="50"/>
		<buffer id="B1_ST03" description="Buffer 1 contains covers" current="10" max="10" warning="5" xPos="520" yPos="580" zPos="40" consumable_id="C1_B1_ST03">
			<consumable id="C1_B1_ST03" description="Cover" type="cover" resourceType="material"/>
		</buffer>
		<tool id="T1_ST03" type="gripper" changeoverT="00:15:00" description="Simple gripper"/>
		<simple_operation id="S_01" type="place_cover" executionTime="00:00:05"/>
		<complex_operation id="C_01" type="assembly" executionTime="00:00:10"/>
</station>

=== alopez244/FlexManSys/classes/resources/ResInstances/Station3.xml
<?xml version="1.0" encoding="UTF-8"?>
<station xmlns="station" id="31" description="Station 3 only has covers as consumable materials" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="station ./Station.xsd">
	<palletIn id="PI1_ST_03" xPos="80" yPos="80" zPos="50"/>
	<palletIn id="PI2_ST_03" xPos="520" yPos="80" zPos="50"/>
	<palletOut id="PO1_ST_03" xPos="620" yPos="380" zPos="50"/>
	<buffer id="B1_ST_03" description="Buffer 1 contains covers" current="10" max="10" warning="5" xPos="520" yPos="580" zPos="40" consumable_id="C1_B1_ST_03">
		<consumable id="C1_B1_ST_03" description="Cover" type="cover"/>
	</buffer>
	<tool id="T1_ST_03" type="gripper" changeoverT="00:15:00" description="Simple gripper"/>
	<simple_operation id="10" executionTime="00:00:15">
		<action id="4" type="pick_and_place" actionPos="4" description="place cover">
			<consumable id="C" description="Cover" type="cover"/>
		</action>
	</simple_operation>
</station>
